kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: nas_vcs_api
  namespace: nas_vcs_1
  version: '1.0'
  tags: 
    - nas_vcs
  type: REST
spec:
  api-spec:
    $path: nas_vcs_api-spec.yml
  policy-sequence: []
